
CREATE TABLE MOVIE (
    MOVIE_ID      NUMBER PRIMARY KEY,
    TITLE         VARCHAR2(50) NOT NULL,
    GENRE         VARCHAR2(20) NOT NULL
);

-- MOVIE 테이블에 사용할 시퀀스 생성
CREATE SEQUENCE SEQ_MOVIE_ID;

-- 2. 리뷰 테이블 (REVIEW) 생성
-- MOVIE_ID 컬럼을 추가하고, 이를 외래 키로 사용합니다.
CREATE TABLE REVIEW (
    REVIEW_NO     NUMBER PRIMARY KEY,
    REVIEW_ID     VARCHAR2(30) NOT NULL UNIQUE,
    REVIEW_PWD    VARCHAR2(30) NOT NULL,
    MOVIE_TITLE   VARCHAR2(50) NOT NULL,
    MOVIE_ID      NUMBER NOT NULL,                  
    RATING        NUMBER(1) CHECK (RATING >= 1 AND RATING <= 5),
    CREATE_DATE   DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT FK_MOVIE_ID FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(MOVIE_ID)
);


-- REVIEW 테이블에 사용할 시퀀스 생성
CREATE SEQUENCE SEQ_REVIEW_NO;


--영화테이블에 넣기
INSERT INTO MOVIE
VALUES(SEQ_MOVIE_ID.NEXTVAL,'귀멸의 칼날', '애니메이션'); 

INSERT INTO MOVIE
VALUES(SEQ_MOVIE_ID.NEXTVAL,'F1 더 무비', '액션'); 

INSERT INTO MOVIE
VALUES(SEQ_MOVIE_ID.NEXTVAL,'좀비딸', '코미디'); 

INSERT INTO MOVIE
VALUES(SEQ_MOVIE_ID.NEXTVAL,'첫사랑 엔딩', '로맨드'); 

INSERT INTO MOVIE
VALUES(SEQ_MOVIE_ID.NEXTVAL,'살인자 리포트', '스릴러'); 
COMMIT;

INSERT INTO MOVIE
VALUES(SEQ_MOVIE_ID.NEXTVAL,'컨저링', '스릴러'); 
COMMIT;

INSERT INTO REVIEW
VALUES(SEQ_REVIEW_NO.NEXTVAL,'KH01', 'KH01','F1','5',2,SYSDATE); 

INSERT INTO REVIEW
VALUES(SEQ_REVIEW_NO.NEXTVAL,'KH02', 'KH02','좀비딸','4',3,SYSDATE); 

INSERT INTO REVIEW
VALUES(SEQ_REVIEW_NO.NEXTVAL,'KH03', 'KH03','귀멸의 칼날','5',1,SYSDATE); 


INSERT INTO REVIEW
VALUES(SEQ_REVIEW_NO.NEXTVAL,'KH05', 'KH05','첫사랑 엔딩','4',4, SYSDATE); 

SELECT * FROM MOVIE;


