--1.
SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 이름,         
       TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002';

--2. 이름이 세글자가 아닌 교수 조회
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3.나이추출..
SELECT PROFESSOR_NAME 교수이름, 
EXTRACT(YEAR FROM SYSDATE) - (19 || SUBSTR(PROFESSOR_SSN, 1, 2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 나이;

--4. 성 빼고 이름만 추출
SELECT SUBSTR(PROFESSOR_NAME, 2) 이름
FROM TB_PROFESSOR

--5.